//
//  PtWordList.swift
//  BlaBlaBla
//
//  Created by camila oliveira on 08/04/18.
//  Copyright © 2018 Aliamcami. All rights reserved.
//

import UIKit

struct PtBrWordList: WordList {
    var countries: [String]{
        return "na África, na África do Sul, na Alemanha, na América do Norte, na América do Sul, na Antártida, na Arábia Saudita, na Argentina, na Arménia, na Ásia, na Austrália, na Áustria, na Bahia, na Bélgica, na Bolívia, na China, na Colômbia, na Coreia do Norte, na Coreia do Sul, na Costa do Marfim, na Costa Rica, na Dinamarca, na Espanha, na Etiópia, na Europa, na Finlândia, na França, na Grécia, na Gronelândia, na Guatemala, na Hungria, na Índia, na Indonésia, na Irlanda, na Jamaica, na Jordânia, na Malásia, na Mongólia, na Nigéria, na Noruega, na Nova Zelândia, na Oceania, na Paraíba, na Roménia, na Rondônia, na Rússia, na Síria, na Somália, na Suécia, na Suíça, na Tailândia, na Tanzânia, na Tunísia, na Turquia, na Ucrânia, na Venezuela, nas Bermudas, nas Filipinas, no Acre, no Afeganistão, no Amapá, no Amazonas, no Azerbaijão, no Brasil, no Cabo Verde, no Canadá, no Cazaquistão, no Ceará, no Chile, no Distrito Federal, no Egito, no Equador, no Espírito Santo, no Goiás, no Haiti, no Iraque, no Japão, no Líbano, no Maranhão, no Marrocos, no Mato Grosso, no Mato Grosso do Sul, no México, no Oceano, no Oceano atlantico, no Paquistão, no Pará, no Paraguai, no Paraná, no Peru, no Piauí, no Rio de Janeiro, no Rio Grande do Norte, no Rio Grande do Sul, no Sergipe, no Uruguai, no Vaticano, no Zimbabué, nos Estados Unidos".split(separator: ",").map(String.init)
    }
    
    var places: [String]{
        return "um Aeroporto,  um Avião,  um Banco,  um Bar,  um Caixa Eletrônico,  um Carro,  um Cinema,  um Clube,  um Escritório,  um Hospital,  um Hotel,  um Mercado,  um Museu,  um Ônibus,  um Parque,  um Posto de Gasolina,  um Prédio Comercial,  um Prédio residencial,  um Restaurante,  um salão,  um Shopping,  um Supermercado,  um Teatro,  um Trem,  um Tribunal,  um Zoológico,  uma Açougue,  uma Barbearia,  uma Biblioteca,  uma Casa,  uma Delegacia,  uma Escola,  uma Estação de Metrô,  uma Faculdade,  uma Farmácia,  uma Galeria,  uma Igreja,  uma Joalheria,  uma Lanchonete,  uma Lavandaria,  uma Livraria,  uma Loja,  uma Lotérica,  uma Padaria,  uma Parada de Ônibus,  uma Pista de Boliche,  uma Praça,  uma Prisão,  uma piscina,  uma Quadra de esporte,  uma Rodoviária,  uma Sala de aula,  uma Universidade,  uma rua,  um jardim,  um lugar,  um quarto,  um prédio,  um caminhão,  uma bicicleta".split(separator: ",").map(String.init)
    }
    
    var adjectives: [String]{
        return "animado, apaixonado, calmo, cansado, carente, carinhoso, chateado, com fome, criativo, curioso, encantado, feliz, Molhado, morto, pelado, preso, raivoso, Seco, vivo, grande, bom, mal, pequeno, velho, alto, solitário, estranho, escuro, enorme, diferente, bonito, feio, forte, fraco, pobre, livre, terrível, azul, vermelho, verde, roxo, jovem, gordo, magro, rapido, rico, perfeito, mudo, doente, cego, nervoso, social, normal, horrível, maravilhoso, inútil, infeliz, triste, desagradável, simpático, violento, inteligente, burro, misterioso, doméstico, feroz, delicado, indelicado, grávido, amigo, famoso, elegante, redondo, quadrado, louco, irritado, desesperado, colorido, engraçado, determinado, estúpido, perigoso, frágil, surdo, sincero, doido, magnífico, selvagem , infantil, perdido, divertido, assustado, mágico, cruel, poderoso, invisível, orgulhoso, mudo, esquisito, honesto, universitário, confiante, aflito, zangado, insignificante, incrível, esperto, transparente, chato, legal, envergonhado, irritante, manso, fantástico, bêbado, romântico, insuportável, dramático, acordado, solteiro, casado, indignado, deprimido, barbudo, popular, desajeitado, artificial, exausto, distraído, adulto, idoso, intelectual, sortudo, perfumado, indeciso, corajoso, covarde, ousado, medieval, irresistível, egoísta, cheiroso, inofensivo, perverso, barulhento, apavorado, com medo, exótico".split(separator: ",").map(String.init)
    }
    
    var animals: [String]{
        return "um Cachorro,  um Cavalo,  um Centauro,  um Ciclope,  um Coala,  um Crocodilo,  um Duende,  um Elefante,  um Gafanhoto,  um Gambá,  um Gato,  um Golfinho,  um Leão,  um Lobisomem,  um Lobo,  um Macaco,  um Minotauro,  um Ogro,  um Orc,  um Panda,  um Papagaio,  um Passarinho,  um Polvo,  um Rinoceronte,  um Sapo,  um Touro,  um Unicornio,  um Urso,  um Vampiro,  um Yeti,  uma Abelha,  uma Aranha,  uma Baleia,  uma Cobra,  uma Fada ,  uma Fenix,  uma Galinha,  uma Girafa,  uma Ovelha,  uma Sereia,  uma Tartaruga,  uma Vaca,  um gato,  um mico-leão,  um coelho,  um hamster,  um rato,  um camundongo,  um porco,  um porco da índia,  uma chinchila,  um esquilo,  um piriquito,  um peru,  uma arara,  um jabuti,  um largato,  uma largatixa,  uma serpente,  uma perereca,  uma salamandra,  uma carpa,  um peixe-palhaço,  um carangueijo,  uma tarântula,  um caramujo,  um caracol,  uma joaninha,  uma onça,  um tigre,  uma pantera,  um avestruz,  uma lontra,  um porco-espinho,  uma capivara,  um beija-flor,  uma garça,  uma iguana,  um tucano,  uma libélula,  um ouriço,  um calango,  um pica-pau,  uma sucuri,  um guaxinim,  um canguru,  um monstro,  um elfo,  um anão,  um kraken,  um tiranossauro,  um dragão,  uma borboleta,  uma medusa,  um grifo,  uma hidra,  uma quimera,  um golem,  um gnomo,  uma succubus,  um cachorro de 3 cabeças,  um troll,  um elemental de ar,  um elemental de fogo,  um elemental de terra,  um elemental de água,  um pokemon,  um digimon,  um pikachu".split(separator: ",").map(String.init)
    }
    
    var objects: [String]{
        return "um abajur,  um absorvente,  um aparador,  um armário,  um aspirador de pó,  um Aviao,  um balde,  um banco,  um cabide,  um chuveiro,  um cinzeiro,  um cobertor,  um colchão,  um computador,  um Copo,  um copo,  um cotonete,  um desodorante,  um despertador,  um edredom,  um espelho,  um fio dental,  um fogão,  um forno,  um Garfo,  um garfo,  um geladeira,  um guarda roupas,  um lençol,  um Livro,  um microondas,  um papel de parede,  um papel higiênico,  um pente,  um perfume,  um Prato,  um prato,  um quadro,  um rádio,  um relógio,  um rodo,  um sabonete,  um sofá,  um Tapete,  um tapete,  um telefone,  um travesseiro,  um vaso,  um xampu,  um xícara,  uma almofada,  uma banheira,  uma Borracha,  uma cadeira,  uma cafeteira,  uma Cama,  uma caneca,  uma caneca,  uma Colher,  uma colher,  uma cortina,  uma escova de dente,  uma esponja,  uma estante,  uma Faca,  uma faca,  uma fralda,  uma frigideira,  uma fronha,  uma fruteira,  uma Janela,  uma lâmpada,  uma lava louças,  uma maçaneta,  uma Mesa,  uma mesa,  uma panela,  uma pasta de dente,  uma pia,  uma poltrona,  uma Porta,  uma tábua,  uma televisão,  uma Tesoura,  uma toalha,  uma torneira,  uma vassoura,  um objeto".split(separator: ",").map(String.init)
    }
    
    
}
